### PR TITLE
No err during cleaning if controller isnt deployed

### LINKED ISSUE #2815: Service Catalog cleaner should not fail when controller-manager is not deployed
# Bug Report 

**What happened**:
The service catalog cleaner job fails when `controller-manager` deployment cannot be found. This job is executed as a pre-delete hook.

The problem is that when the svc-cat helm release fails and controller-manager is not installed then release cannot be removed because the cleaner job is executed and fails with not found error. 

**What you expected to happen**:

cleaner job should only ensure that the CRDs and all svcat CRs are removed.  With `ensure` I mean that if they do not exist then it should not fail.

### PR DESCRIPTION
**Pull request by gmrodgers**
This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
- Previously it would error if there were zero deployments, say if
deployment failed.  This is described here in #2815.  I believe this is the same error that we were encountering on our team.  All feedback welcome!

**Which issue(s) this PR fixes** 
Fixes #2815 

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

File: pkg/cleaner/cleaner.go [hunk 1]
```diff
@@ -89,36 +90,35 @@ func (c *Cleaner) RemoveCRDs(releaseNamespace, controllerManagerName string, web
...
-	deploymentCopy.Spec.Replicas = &replicas
-	_, err = c.client.AppsV1().Deployments(deploymentCopy.Namespace).Update(context.Background(), deploymentCopy, v1.UpdateOptions{})
-	if err != nil {
-		return fmt.Errorf("failed to update deployment %s/%s: %v", namespace, controllerName, err)
-	}
-
-	err = wait.Poll(3*time.Second, 120*time.Second, func() (done bool, err error) {
-		klog.V(4).Info("Waiting for deployment scales down...")
-		deployment, err := c.client.AppsV1().Deployments(namespace).Get(context.Background(), controllerName, v1.GetOptions{})
+	if err == nil {
```
Comment (mszostok) [inline pkg/cleaner/cleaner.go:93]: in Go, the happy path should be aligned to the left. Also, we need to adjust the error handling - skip scaling only in case of `not found` and log a proper info message. In case of any other error we need to return it (btw. if err != nil then `deployment` will be nil so in the current implementation it will result in panic). This is an automated migration job so the steps need to be logged just in case of a debug

```go
import apierrors "k8s.io/apimachinery/pkg/api/errors"
// ...

	switch {
	case err == nil:
	case apierrors.IsNotFound(err):
		klog.V(4).Info("Deployment not found. Skippking scale down to zero.")
		return nil
	default:
		return fmt.Errorf("cannot get deployment %s/%s: %s", namespace, controllerName, err)
	}

// rest of the happy path
```

File: pkg/cleaner/cleaner_test.go [hunk 2]
```diff
@@ -70,6 +70,33 @@ func TestCleaner_RemoveCRDs(t *testing.T) {
 	assert.Len(t, vwcList.Items, 1)
 }
 
+func TestCleaner_RemoveCRDsNoDeployment(t *testing.T) {
```
Comment (mszostok) [inline pkg/cleaner/cleaner_test.go:73]: +1 for test coverage 👍

File: pkg/cleaner/cleaner.go (hunk 1 above)
Comment (gmrodgers) [reply pkg/cleaner/cleaner.go]: Put in your changes, lemme know what you think!

Comment (mszostok) [reply pkg/cleaner/cleaner.go]: nice, lgtm 👍
